### ISSUE TITLE
Is there anyway to send a message from a service worker?

### ISSUE THREAD

**Issue by dodyg** [LostBeard/SpawnDev.BlazorJS#17]
It's not very clear from this whether it is possible to send a message from `IMathService`.

![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/1761249/b9c27981-a564-48cd-b695-fb095ae50379)

According to this `PostEvent` is only available via the worker itself. 
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/1761249/65d83939-2f32-4192-bd04-7b5a8a5970d1)

**Comment by LostBeard** [comment]
> According to this PostEvent is only available via the worker itself.

I'm not sure where the misunderstanding lies here. Hopefully this clears it up.

## Option 1
In your window context
```cs
var worker = await workerService.GetWebWorker();
worker.OnMessage += (sender, msg) =>
{
    // use msg.TargetName to get the message identifier used as the first parameter in ```SendEventToParents```
    if (msg.TargetName == "progress")
    {
        PiProgress msgData = msg.GetData<PiProgress>();
        piProgress = msgData.Progress;
        StateHasChanged();
    }
};
```

In your WebWorker context to send a message to the window that is listening
```cs
workerService.SendEventToParents("progress", new PiProgress { Progress = piProgress });
```

That code shows how a window can listen to messages from the worker and how to send messages to the window listening for those messages.

## Option 2 (WebWorker only, not available in SharedWebWorker)
Another option is to use ```WebWorkerService.DedicatedWorkerParent``` from inside a WebWorker.

WebWorkerService.DedicatedWorkerParent is equivalent to WebWorkerService.GetWebWorker except the returned value points to the Window context that created the WebWorker instead of a new WebWorker.

From inside a WebWorker context, to get an interface that allows calling a Service on the Window context from a WebWorker context just like a Window can do with a WebWorker. 
 ```cs 
// get a handle to the service interface ISomeWindowService in the Window context
var someWindowService = WebWorkerService.DedicatedWorkerParent.GetService<ISomeWindowService>(); 
// call a method on the window context
await someWindowService.SomeMethod();
``` 
Hopefully that helps. If you see a way to make the documentation more understandable please let me know. Thank you.

**Comment by LostBeard** [comment]
Yes. Option 1 and Option 2 I described above.

**Comment by LostBeard** [comment]
The window that created the WebWorker should already have a handle to eat and can message it. 

Give me a moment. I believe there is also a way that you can get a reference to the calling context.

**Comment by LostBeard** [comment]
```cs
public interface ISomeWindowService 
{
   Task DoSomethingAsync();
}

public class SomeWindowService: ISomeWindowService
{
   public async Task DoSomethingAsync(ServiceCallDispatcher caller)
   {
       // caller will be the WebWorker context that called the method. 
   }
}
```

**Comment by LostBeard** [comment]
That mechanism works in a WebWorker, SharedWebWorker, and Window contexts to get the caller context.

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/issues/377

**Comment by dodyg** [comment]
Thank you so much for your help. This is a brilliant library.

**Comment by LostBeard** [comment]
Thank you and glad to help. I will continue to work on improving the documentation. Some of these advanced features haven't quite made it into the docs yet but should be there soon.
